feat: ts refactor, filter stack trace, update pretty
voiceflow/logger pull request #10
Opened 2020-12-21 15:21 UTC by z4o4z

2020-12-21 16:49 UTC, frankgu968 commented on package.json
>      "@voiceflow/pino-pretty": "^3.5.0",
Update this one after merging the pino-pretty changes

2020-12-21 16:50 UTC, frankgu968 commented
Can you please fix the call stack test(s) as well? I think the paths changed so you'll have to update the references

2020-12-21 16:58 UTC, DecathectZero submitted a review, later dismissed

2021-01-04 15:30 UTC, frankgu968 requested changes
@z4o4z I see that you have removed the Caller identification code, but I don't see any refactor into TS. How is the callstack identified now?? Is it part of Pino's log??

2021-01-04 15:45 UTC, frankgu968 approved these changes

2021-01-05 09:39 UTC, merged

2021-01-05 09:42 UTC, voiceflow-dev commented
:tada: This PR is included in version 1.4.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@voiceflow/logger/v/1.4.2)
- [GitHub release](https://github.com/voiceflow/logger/releases/tag/v1.4.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: